services:
  - type: web
    name: scaler-november-7
    runtime: node
    rootDir: class-42-bms
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
